apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "cve-processor.fullname" . }}
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/logLevel: debug
        sidecar.istio.io/componentLogLevel: "ext_authz:debug,filter:debug"
        proxy.istio.io/config: '{"holdApplicationUntilProxyStarts": true}'
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Values.container.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              {{- if .valueFrom }}
              valueFrom:
                {{- toYaml .valueFrom | nindent 16 }}
              {{- else }}
              value: {{ .value | quote }}
              {{- end }}
            {{- end }}
      imagePullSecrets:
        - name: docker-hub-pat