apiVersion: v1
kind: Pod
metadata:
  name: {{ include "cve-processor.fullname" . }}
spec:
  initContainers:
    - name: flyway-migration
      image: "{{ .Values.initContainer.image.repository }}:{{ .Values.initContainer.image.tag }}"
      env:
        {{- range .Values.initContainer.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
      command: ["flyway", "migrate"]
  containers:
    - name: {{ .Values.container.name }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
      env:
        {{- range .Values.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
      livenessProbe:
        {{- toYaml .Values.livenessProbe | nindent 8 }}
      readinessProbe:
        {{- toYaml .Values.readinessProbe | nindent 8 }}
  imagePullSecrets:
    - name: docker-hub-pat 
        