apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cve-processor-rolebinding
  namespace: cve-processor
subjects:
- kind: ServiceAccount
  name: cve-processor-sa
  namespace: cve-processor
roleRef:
  kind: Role
  name: cve-processor-role
  apiGroup: rbac.authorization.k8s.io