apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cve-processor-hpa
  namespace: cve-processor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cve-processor-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50